# Travis CI configuration file.

language: php

php:
    - 5.6
    - 7.0

before_script:
    - composer install

script:
    - vendor/bin/codecept run unit --coverage-xml clover.xml

after_success:
    - vendor/bin/coveralls
